### ISSUE TITLE
Python version?

### ISSUE THREAD

**Issue by chagyun0213** [BingzheWu/object_detetction_tools#3]
Hi 
I have the following error. Have to use Python2 or Python3?

nn_model_transform$ python darknet2caffe.py ../yolo3/yolov3.cfg ../yolo3/yolov3.weights ../yolo3/deploy.prototxt ../yolo3/yolov3.caffemodel
Traceback (most recent call last):
  File "darknet2caffe.py", line 6, in <module>
    from prototxt_utils import *
  File "nn_model_transform/prototxt_utils.py", line 151
    print('%s%s {' % (blanks, prefix), end = "\n", file = fp)
                                           ^
SyntaxError: invalid syntax

**Comment by BingzheWu** [comment]
The current version only supports Python3

**Comment by chagyun0213** [comment]
Thanks.
